### PR TITLE
Input rework + gamepad support (WIP)

### PR DESCRIPTION
**Pull request by Rorkh**
Changed keybindings schema to support multiple input sources and reworked Gamestate.keypressed. Now Gamestate.buttonpressed receives info from love.keypressed and love.gamepadpressed.

Task list:

- [x] Fix controls settings
- [x] Bind more commands to gamepad keys, make it fully playable (at this state you can interact with ui and walk)
- [x] Make some versioning for keybindings so it can be automatically updated without need to delete prefs.sav if outdated

Don't merge in this state. Opened for discussion.

### CODE REVIEW

**Comment by Rorkh** [comment]
Also to note, I had a trouble making it work with joycons connected by Bluetooth to my PC. After few hours I found a solutions - updated LOVE (to 11.5) from latest dev build. Seems like 11.4 doesn't support joycons (and maybe some other controllers). Need to take in note and update Makefiles later with it in mind.

**Comment by Rorkh** [comment]
Made that prefs file will be deleted if it's outdated. Suggest to make something like migrations later, because now it's seems like an overcomplication for current state of project.

**Comment by vaughantay** [comment]
> Made that prefs file will be deleted if it's outdated. Suggest to make something like migrations later, because now it's seems like an overcomplication for current state of project.

I'm not sure this is necessary, unless I'm missing something.

Currently, settings and keybindings are set in load_prefs() in saveload.lua, which is called when the game first loads. The default settings and keybindings are loaded first, and then any saved keybindings and settings are applied.
So if new keybindings or settings are added that prefs.sav has no information about, it applies the defaults for them (and then saves them in prefs.sav when the game closes).

**Comment by Rorkh** [comment]
> > Made that prefs file will be deleted if it's outdated. Suggest to make something like migrations later, because now it's seems like an overcomplication for current state of project.
> 
> I'm not sure this is necessary, unless I'm missing something.
> 
> Currently, settings and keybindings are set in load_prefs() in saveload.lua, which is called when the game first loads. The default settings and keybindings are loaded first, and then any saved keybindings and settings are applied. So if new keybindings or settings are added that prefs.sav has no information about, it applies the defaults for them (and then saves them in prefs.sav when the game closes).

I changed the layout how keys is added. command[1] was used but command.keyboard[1] or command.gamepad[1] is used now.
So it's necessary. Layout in code has changed but prefs.sav can have old one.

**Comment by vaughantay** [comment]
> > > Made that prefs file will be deleted if it's outdated. Suggest to make something like migrations later, because now it's seems like an overcomplication for current state of project.
> > 
> > 
> > I'm not sure this is necessary, unless I'm missing something.
> > Currently, settings and keybindings are set in load_prefs() in saveload.lua, which is called when the game first loads. The default settings and keybindings are loaded first, and then any saved keybindings and settings are applied. So if new keybindings or settings are added that prefs.sav has no information about, it applies the defaults for them (and then saves them in prefs.sav when the game closes).
> 
> I changed the layout how keys is added. command[1] was used but command.keyboard[1] or command.gamepad[1] is used now. So it's necessary. Layout in code has changed but prefs.sav can have old one.

OK. I can see how it'd be useful to have a feature like that in the case of big structural changes like this.
For an in-development developer-facing situation like this it's fine to break stuff but I don't want end users' entire preferences files getting deleted every time there's a new setting added.
But I guess that's really up to the developers of the games themselves to use it responsibly, so I'll add some sort of documentation around it.

**Comment by Rorkh** [comment]
I consider PR done. Buttons not fully binded but again I want to return to it after UI rework (plan as my next PR) because changes in UI required. I want make ability to switch to right part on game screen and use keys to switch between buttons.

**Pull request merged**
